//! Common language-model response and token-usage types.
use std::collections::HashMap;

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone, Default)]
/// Text generated by a language model and its optional token usage.
pub struct GenerateResult {
    /// Token counts reported by the model provider, when available.
    pub tokens: Option<TokenUsage>,
    /// Generated text.
    pub generation: String,
}

impl GenerateResult {
    /// Converts the generation and available token counts into string values.
    pub fn to_hashmap(&self) -> HashMap<String, String> {
        let mut map = HashMap::new();

        // Insert the 'generation' field into the hashmap
        map.insert("generation".to_string(), self.generation.clone());

        // Check if 'tokens' is Some and insert its fields into the hashmap
        if let Some(ref tokens) = self.tokens {
            map.insert(
                "prompt_tokens".to_string(),
                tokens.prompt_tokens.to_string(),
            );
            map.insert(
                "completion_tokens".to_string(),
                tokens.completion_tokens.to_string(),
            );
            map.insert("total_tokens".to_string(), tokens.total_tokens.to_string());
        }

        map
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, Default)]
/// Token counts consumed by a language-model request.
pub struct TokenUsage {
    /// Tokens in the request prompt.
    pub prompt_tokens: u32,
    /// Tokens generated in the response.
    pub completion_tokens: u32,
    /// Total prompt and completion tokens.
    pub total_tokens: u32,
}

impl TokenUsage {
    /// Returns the saturating field-wise sum of two usage records.
    pub fn sum(&self, other: &TokenUsage) -> TokenUsage {
        TokenUsage {
            prompt_tokens: self.prompt_tokens.saturating_add(other.prompt_tokens),
            completion_tokens: self
                .completion_tokens
                .saturating_add(other.completion_tokens),
            total_tokens: self.total_tokens.saturating_add(other.total_tokens),
        }
    }

    /// Adds another usage record to this one using saturating arithmetic.
    pub fn add(&mut self, other: &TokenUsage) {
        self.prompt_tokens = self.prompt_tokens.saturating_add(other.prompt_tokens);
        self.completion_tokens = self
            .completion_tokens
            .saturating_add(other.completion_tokens);
        self.total_tokens = self.total_tokens.saturating_add(other.total_tokens);
    }
}

impl TokenUsage {
    /// Creates usage counts and computes the total with saturating addition.
    pub fn new(prompt_tokens: u32, completion_tokens: u32) -> Self {
        Self {
            prompt_tokens,
            completion_tokens,
            total_tokens: prompt_tokens.saturating_add(completion_tokens),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn token_usage_sum_saturates() {
        let a = TokenUsage {
            prompt_tokens: u32::MAX,
            completion_tokens: u32::MAX,
            total_tokens: u32::MAX,
        };
        let b = TokenUsage {
            prompt_tokens: 1,
            completion_tokens: 1,
            total_tokens: 1,
        };
        let result = a.sum(&b);
        assert_eq!(result.prompt_tokens, u32::MAX);
        assert_eq!(result.completion_tokens, u32::MAX);
        assert_eq!(result.total_tokens, u32::MAX);
    }

    #[test]
    fn token_usage_add_saturates() {
        let mut a = TokenUsage {
            prompt_tokens: u32::MAX,
            completion_tokens: u32::MAX,
            total_tokens: u32::MAX,
        };
        let b = TokenUsage {
            prompt_tokens: 1,
            completion_tokens: 1,
            total_tokens: 1,
        };
        a.add(&b);
        assert_eq!(a.prompt_tokens, u32::MAX);
        assert_eq!(a.completion_tokens, u32::MAX);
        assert_eq!(a.total_tokens, u32::MAX);
    }

    #[test]
    fn token_usage_new_saturates() {
        let t = TokenUsage::new(u32::MAX, 1);
        assert_eq!(t.total_tokens, u32::MAX);
    }
}
